sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project dm-creation-project-313814
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials k8s-demo-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t datariomj/react-test -f ./client/Dockerfile.dev
script:
  - docker run -e CI=true datariomj/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
      branch: main